prefix owl: <http://www.w3.org/2002/07/owl#>
prefix schema: <https://schema.org/>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?project ?platform
WHERE {
    ?project rdf:type ?projectType.
    ?projectType rdfs:label ?projectTypeLabel.
    FILTER(?projectTypeLabel = "Project").

    OPTIONAL {
        ?project ?usesPlatform ?platform.
        ?usesPlatform rdfs:label ?usesPlatformLabel.
        FILTER(?usesPlatformLabel = "Uses platform").
    }
}
